require: rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  Rails:
    Enabled: true
  Exclude:
    - db/**/*
    - config/initializers/devise.rb
    - bin/**/*
    - vendor/**/*
    - config/routes.rb

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
