services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/app
      - ./db:/blog/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - sidekiq
    volumes:
      - .:/app
      - ./db:/blog/db
