# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/internal/linkedin_schedulers', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Internal::LinkedinScheduler. As you add validations to Internal::LinkedinScheduler, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Internal::LinkedinScheduler.create! valid_attributes
      get internal_linkedin_schedulers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
      get internal_linkedin_scheduler_url(linkedin_scheduler)
      expect(response).to be_successful
    end
  end

  # describe 'GET /new' do
  #   it 'renders a successful response' do
  #     get new_internal_linkedin_scheduler_url
  #     expect(response).to be_successful
  #   end
  # end

  describe 'GET /edit' do
    it 'renders a successful response' do
      linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
      get edit_internal_linkedin_scheduler_url(linkedin_scheduler)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Internal::LinkedinScheduler' do
        expect do
          post internal_linkedin_schedulers_url, params: { internal_linkedin_scheduler: valid_attributes }
        end.to change(Internal::LinkedinScheduler, :count).by(1)
      end

      it 'redirects to the created internal_linkedin_scheduler' do
        post internal_linkedin_schedulers_url, params: { internal_linkedin_scheduler: valid_attributes }
        expect(response).to redirect_to(internal_linkedin_scheduler_url(Internal::LinkedinScheduler.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Internal::LinkedinScheduler' do
        expect do
          post internal_linkedin_schedulers_url, params: { internal_linkedin_scheduler: invalid_attributes }
        end.to change(Internal::LinkedinScheduler, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post internal_linkedin_schedulers_url, params: { internal_linkedin_scheduler: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested internal_linkedin_scheduler' do
        linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
        patch internal_linkedin_scheduler_url(linkedin_scheduler),
              params: { internal_linkedin_scheduler: new_attributes }
        linkedin_scheduler.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the internal_linkedin_scheduler' do
        linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
        patch internal_linkedin_scheduler_url(linkedin_scheduler),
              params: { internal_linkedin_scheduler: new_attributes }
        linkedin_scheduler.reload
        expect(response).to redirect_to(internal_linkedin_scheduler_url(linkedin_scheduler))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
        patch internal_linkedin_scheduler_url(linkedin_scheduler),
              params: { internal_linkedin_scheduler: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested internal_linkedin_scheduler' do
      linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
      expect do
        delete internal_linkedin_scheduler_url(linkedin_scheduler)
      end.to change(Internal::LinkedinScheduler, :count).by(-1)
    end

    it 'redirects to the internal_linkedin_schedulers list' do
      linkedin_scheduler = Internal::LinkedinScheduler.create! valid_attributes
      delete internal_linkedin_scheduler_url(linkedin_scheduler)
      expect(response).to redirect_to(internal_linkedin_schedulers_url)
    end
  end
end
