development:
  adapter: redis
  url: <%= "#{ENV.fetch("REDIS_URL_ACTION_CABLE","redis://localhost:6379")}/1" %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= "#{ENV.fetch("REDIS_URL_ACTION_CABLE","redis://localhost:6379")}/1" %>
  channel_prefix: blog_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
